modLoader = "javafml"
loaderVersion = "[2,)"
license = "MIT"

[[mods]]
modId = "stonewalled"
version = "1.0-normal"
displayName = "StoneWalled"
authors = "MrPotato"
description = ""

[[mixins]]
config = "stonewalled.mixins.json"
